from .tables import (
    ATTDN_RAW,
    ATTDN_TABLENAMES,
    ATTDN_TABLE_SCHEMAS,

    BPM_RAW,
    BPM_TABLENAMES,
    BPM_TABLE_SCHEMAS,

    EXAMPLE_RAW,
    EXAMPLE_TABLENAMES,
    EXAMPLE_TABLE_SCHEMAS,
)